name: app
description: A markdown note-taking app for mobile devices.
publish_to: none
version: 1.4.6+146

environment:
  sdk: '>=2.7.0 <2.12.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.3.4
  path_provider: ^1.6.27
  yaml: ^2.2.1
  material_design_icons_flutter: ^4.0.5955
  markd:
    git: https://github.com/redsolver/markd.git
  bsdiff: ^0.1.0
  webview_flutter: ^1.0.7
  preferences: ^3.0.1
  html: ^0.14.0+3
  url_launcher: ^5.7.10
  package_info: ^0.4.3+4
  provider: ^4.3.3
  front_matter: ^1.1.0
  flutter_slidable: ^0.5.7
  file_picker: ^1.13.3
  rich_code_editor:
    git: https://github.com/bats64mgutsi/rich_code_editor.git
  device_info: ^0.4.2+9
  quick_actions: ^0.4.0+11
  receive_sharing_intent: ^1.3.3
  quiver: ^2.1.5
  intl: ^0.16.1
  permission_handler: ^5.1.0+2
  uuid: ^2.2.2

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/tutorial/notes/
    - assets/tutorial/attachments/
    - assets/preview/fonts/
    - assets/preview/

  fonts:
    - family: FiraMono
      fonts:
        - asset: assets/fonts/FiraMono-Regular.ttf
