name: app
description: A markdown note-taking app for mobile devices.
publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.6+146

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.4.2
  path_provider: ^2.0.0
  yaml: ^2.2.0
  material_design_icons_flutter: ^4.0.5045
  markd:
    git: https://github.com/redsolver/markd.git
  # flutter_widget_from_html: ^0.3.3
  bsdiff: ^0.1.0
  webview_flutter: ^1.0.1
  # flutter_i18n: ^0.7.0
  preferences: ^5.2.0
  html: ^0.14.0+2
  url_launcher: ^6.0.2
  package_info: ^0.4.0+8

  provider: ^4.0.5+1

  front_matter: ^1.1.0
  flutter_slidable: ^0.5.4
  #time_machine: ^0.9.9
  file_picker: ^3.0.0
  rich_code_editor:
    git: https://github.com/bats64mgutsi/rich_code_editor.git
  device_info: ^2.0.0
  quick_actions: ^0.4.0+8
  receive_sharing_intent: ^1.4.1
  quiver: ^3.0.0
  intl: ^0.17.0
  permission_handler: ^6.1.0
  uuid: ^3.0.3

dependency_overrides:
  shared_preferences: ^2.0.4
# dev_dependencies:
# flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_ios.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tutorial/notes/
    - assets/tutorial/attachments/
    #    - assets/i18n/
    - assets/preview/fonts/
    - assets/preview/

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FiraMono
      fonts:
        - asset: assets/fonts/FiraMono-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
