# ワークフローの名前
name: Build Android APK

# ワークフローが実行されるタイミングを定義
on:
  push:
    branches:
      - main
  workflow_dispatch:

# 実行する一連のタスク（ジョブ）を定義
jobs:
  build:
    # ジョブを実行する仮想環境の種類（Ubuntuの最新版）
    runs-on: ubuntu-latest

    # ジョブの中の個別の手順（ステップ）
    steps:
      # 1. あなたのリポジトリの最新のコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Java Development Kit (JDK 11) をセットアップする
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Flutter SDK (2.2.3) をセットアップする
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'
          cache: true

      # 4. Flutterの依存パッケージをインストールする
      - name: Install Flutter dependencies
        run: flutter pub get

      # 5. build.gradleから署名設定を削除する
      - name: Remove signing configuration from build.gradle
        run: |
          sed -i "/storeFile file(keystoreProperties/d" android/app/build.gradle
          sed -i "/signingConfig signingConfigs.release/d" android/app/build.gradle

      # 6. AndroidのAPKファイルをビルドする
      - name: Build APK
        run: flutter build apk --release

      # 7. ビルドされたAPKファイルをアーティファクトとしてアップロードする
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: noteless-apk
          path: build/app/outputs/flutter-apk/app-release.apk
