# ワークフローの名前
name: Build Android APK

# ワークフローが実行されるタイミングを定義
on:
  # 'Actions' タブから手動で実行できるようにする
  workflow_dispatch:
  # mainブランチにプッシュされた時にも自動で実行する
  push:
    branches:
      - main

# 実行する一連のタスク（ジョブ）を定義
jobs:
  build:
    # ジョブを実行する仮想環境の種類（Ubuntuの最新版）
    runs-on: ubuntu-latest

    # ジョブの中の個別の手順（ステップ）
    steps:
      # 1. リポジトリのソースコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Java Development Kit (JDK) をセットアップする (FlutterのAndroidビルドに必要)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Flutter SDKをセットアップする
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.5.5' # 安定版のFlutterを使用

      # 4. Flutterの依存パッケージをインストールする
      - name: Install Flutter dependencies
        run: flutter pub get

      # 5. AndroidのAPKファイルをビルドする（リリースモード）
      - name: Build APK
        run: flutter build apk --release

      # 6. ビルドされたAPKファイルをアーティファクトとしてアップロードする
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: noteless-apk # ダウンロードされるファイル名の一部になる
          path: build/app/outputs/flutter-apk/app-release.apk # ビルドされたAPKファイルの場所
